# Generated by Django 3.2.25 on 2026-01-17 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AQIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('aqi_value', models.IntegerField()),
                ('pm25', models.FloatField(verbose_name='PM2.5')),
                ('pm10', models.FloatField(verbose_name='PM10')),
                ('traffic_contribution', models.FloatField(default=0)),
                ('industrial_contribution', models.FloatField(default=0)),
                ('crop_burning_contribution', models.FloatField(default=0)),
                ('construction_contribution', models.FloatField(default=0)),
                ('other_contribution', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'AQI Data',
                'verbose_name_plural': 'AQI Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AQIForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('forecast_date', models.DateTimeField()),
                ('predicted_aqi', models.IntegerField()),
                ('confidence', models.FloatField(help_text='Prediction confidence (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('policy_type', models.CharField(choices=[('TRAFFIC', 'Traffic Management'), ('INDUSTRY', 'Industrial Control'), ('CONSTRUCTION', 'Construction Regulation'), ('FIRECRACKER', 'Firecracker Ban'), ('CROP_BURNING', 'Crop Burning Control'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('UNDER_REVIEW', 'Under Review'), ('IMPLEMENTED', 'Implemented'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=20)),
                ('agree_count', models.IntegerField(default=0)),
                ('disagree_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_respiratory_issues', models.BooleanField(default=False, verbose_name='Respiratory Issues (Asthma, COPD)')),
                ('has_heart_disease', models.BooleanField(default=False, verbose_name='Heart Disease')),
                ('has_allergies', models.BooleanField(default=False, verbose_name='Allergies')),
                ('is_elderly', models.BooleanField(default=False, verbose_name='Age 60+')),
                ('is_child', models.BooleanField(default=False, verbose_name='Age below 12')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='Pregnant')),
                ('location', models.CharField(blank=True, help_text='Area in Delhi NCR', max_length=100)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('SEVERE', 'Severe Risk')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('AGREE', 'Agree'), ('DISAGREE', 'Disagree')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'policy')},
            },
        ),
    ]
