# Generated by Django 3.2.25 on 2026-01-17 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAQIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aqi_images/%Y/%m/%d/')),
                ('location', models.CharField(blank=True, help_text='Where was this photo taken?', max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('predicted_aqi', models.IntegerField(help_text='AQI predicted from image')),
                ('base_aqi', models.IntegerField(blank=True, help_text='Current AQI from sensors', null=True)),
                ('aqi_rise', models.IntegerField(help_text='Estimated AQI increase from pollution source')),
                ('haziness_score', models.FloatField(help_text='Haziness/visibility score (0-1)')),
                ('pollution_source', models.CharField(choices=[('SMOKE', 'Smoke'), ('DUST', 'Dust'), ('VEHICLE', 'Vehicle Emissions'), ('INDUSTRIAL', 'Industrial'), ('CONSTRUCTION', 'Construction'), ('FIRE', 'Fire/Burning'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('health_alert_level', models.CharField(choices=[('LOW', 'Low Impact'), ('MODERATE', 'Moderate Impact'), ('HIGH', 'High Impact'), ('SEVERE', 'Severe Impact')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image AQI Prediction',
                'verbose_name_plural': 'Image AQI Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
